import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-7xl mx-auto px-5">{children}</main>
      </body>
    </html>
  );
}
